    language: node_js

    sudo: false
    dist: trusty

    node_js:
      - '6'
      - '7'
      - '8'

    cache:
      directories:
        - node_modules

    branches:
      only:
      - master

  
    before_install:
      - npm i -g npm@latest

    install:
      - travis_retry npm i


    git:
      depth: 1
